spring-cloud/spring-cloud-commons

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RestTemplateCustomizer.java
By default, creates a RestTemplateCustomizer adds a LoadBalancerInterceptor
fixes gh-16
=> RestTemplateCustomizer to customize the @LoadBalanced RestTemplate.

spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java
Refer to notes in https://github.com/spring-cloud/spring-cloud-commons/issues/49 for details
=> isRefreshScoped returns false if beanName is null

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Given the following in one property source
```
mine[0].someValue=Foo
mine[0].someKey={cipher}XXXX
mine[1].someValue=Bar
mine[1].someKey={cipher}XXXX
yours[0].anotherKey=Baz
```
only `mine[*].someKey` were added to "decrypted" property source. Due to house spring boot manages indexed properties, they can not be merged across property source. This change includes all indexed properties in the "decrypted" property source if any one of them is encrypted.
In the above example, `yours[*].*` is included even though unrelated.
fixes https://github.com/spring-cloud/spring-cloud-config/issues/466
/cc @dsyer @philwebb
=> Fixes indexed properties merging problem.

spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshEndpointAutoConfiguration.java
=> Make sure we copy variables to new InfoEndpoint

spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/named/NamedContextFactoryTests.java
Fixes https://github.com/spring-cloud/spring-cloud-netflix/issues/1585.
=> Exposing context names

spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java
Fixes #151 : HostInfo now has public constructors and is not marked as final
=> GH-151: HostInfo is now extensible

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRetryProperties.java
=> Set spring.cloud.loadbalancer.retry.enabled to true by default

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRetryPolicy.java
Part of the fix to address spring-cloud/spring-cloud-netflix#1540
=> Add retryable status code check

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryableStatusCodeException.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
Also makes it easier to provide your own interceptor by creating two auto configuration classes..  Fixes #215.
=> Retry requests on specified status codes

spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/DiscoveryClient.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClient.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientAutoConfiguration.java, spring-cloud-commons/src/main/resources/META-INF/spring.factories, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientAutoConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/DiscoveryClientAutoConfigurationDefaultTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientPropertiesMappingTests.java
#140 - Added support for a composite Discovery Client
=> GH-140: Support for Composite Discovery client

spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/LifecycleMvcEndpointAutoConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshEndpointAutoConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/context/restart/RestartEndpoint.java, spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/LifecycleMvcAutoConfigurationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationClassPathTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationTests.java
=> Disables endpoint creation

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
=> Create a new RetryTemplate for each request

spring-cloud-commons/pom.xml, spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/actuator/FeaturesEndpoint.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/actuator/NamedFeature.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/health/DiscoveryClientHealthIndicator.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/noop/NoopDiscoveryClientAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/CloudHypermediaAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DiscoveredResource.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DynamicServiceInstanceProvider.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/RemoteResourceRefresher.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/StaticServiceInstanceProvider.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtilsProperties.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/SpringFactoryImportSelector.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AbstractLoadBalancerAutoConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerAutoConfigurationTests.java
Removed dependence on lombok library and changed code to account for the lombok generated methods/fields.
=> Remove dependence on lombok

spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientConnectionManagerFactory.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientConnectionManagerFactoryTests.java
fixing https://github.com/spring-cloud/spring-cloud-commons/issues/251
=> Add SSL support for connection factory with SSL validation

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryableStatusCodeException.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
#271 
this PR help to fix the problem of spring-cloud-netflix #2353
=> add response and uri field to RetryableStatusCodeException

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRetryListenerFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
Hi @ryanjbaxter 
Thank you very much for your patience guidance, and I have re-submitted PR as you suggested (PR #293 has been closed before).
Allow me to explain this PR content
- Add spring-retry listener features
- Added test code for this feature
I hope you can help me check, any of your reply is a great encouragement to me. Thanks again : )
=> Supplement spring-retry listener features

spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClient.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultOkHttpClientFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/OkHttpClientFactory.java
- Remove useless import
- Using a more friendly way of judging
=> Minor changes

spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AutoServiceRegistrationAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/ApacheHttpClientFactory.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/CustomHttpClientConfigurationTests.java
=> Remove invalid import

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/pom.xml, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/DefaultOkHttpClientFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/HttpClientConfiguration.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/CustomHttpClientBuilderConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/CustomOkHttpClientBuilderConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/DefaultApacheHttpClientFactoryTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/httpclient/DefaultOkHttpClientFactoryTest.java
Allows the ability to provide a customer http client builder.
=> Allows for custom Http Client builders

spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
=> Give application context a friendly display name.

.github/CONTRIBUTING.md, docs/src/main/asciidoc/spring-cloud-commons.adoc
Fixed #53 & #310
Also fixed some linking issues with `CONTRIBUTING.md`
=> Documentation fixes

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/KeyProperties.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/RsaProperties.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfigurationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/RsaDisabledTests.java
Avoids ClassNotFoundException when RSA is not on the classpath.  Fixes #334.
=> Move RSA properties to its own class and make it conditional

docs/src/main/asciidoc/spring-cloud-commons.adoc
=> Document how to expose refresh endpoint

spring-cloud-commons/pom.xml, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/HttpClientConfiguration.java
=> Make Apache HTTP Client optional

spring-cloud-context/src/main/java/org/springframework/cloud/context/restart/RestartEndpoint.java
Previous implementation did the same. Current is only stopping the instance for me, fails to start it again. With this fix it is working as expected.
=> RestartEndpoint fixed

spring-cloud-context/src/main/java/org/springframework/cloud/health/RefreshScopeHealthIndicator.java, spring-cloud-context/src/test/java/org/springframework/cloud/health/RefreshScopeHealthIndicatorTests.java
=> Add null check in RefreshScopeHealthIndicator

spring-cloud-commons/src/main/resources/META-INF/additional-spring-configuration-metadata.json
=> Adding additional-spring-configuraition-metadata.json

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/event/InstancePreRegisteredEvent.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistration.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistrationTests.java
=> Adds event that will be fired before a service is registered

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerExchangeFilterFunction.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerExchangeFilterFunctionTests.java
=> Return a client response from filter function 

spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
Fixes https://github.com/spring-cloud/spring-cloud-config/issues/1167
=> Check type before invoking bean factory 

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
=> Closes bootstrap context on parent ApplicationFailedEvent.

spring-cloud-commons/src/main/resources/META-INF/additional-spring-configuration-metadata.json, spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/WritableEnvironmentEndpointAutoConfiguration.java
=> Add property to disable WritableEnvironmentEndpoint

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
=> Trim profile names in array

spring-cloud-loadbalancer/pom.xml
reactor-extra has released since this TODO comment was made.
=> Update to RELEASE version of dependency

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/BootstrapEnvironmentPostProcessorIntegrationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderIntegrationTests.java, spring-cloud-context/src/test/resources/META-INF/spring.factories
=> Ignores MapPropertySources not created by boot

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/KeyProperties.java
Supports fix in https://github.com/spring-cloud/spring-cloud-config/pull/1258
=> Add new type property to KeyStore properties

.github/CONTRIBUTING.md, README.adoc, docs/src/main/asciidoc/intro.adoc, docs/src/main/asciidoc/jce.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/EnableCircuitBreaker.java
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were fixed, but the https status was not OK. However, the https status was the same as the http request or http redirected to an https URL, so they were migrated. Your review is recommended.
https://compose.docker.io/ ([https](https://compose.docker.io/) result UnknownHostException).
https://www.puppycrawl.com/dtds/suppressions_1_1.dtd ([https](https://www.puppycrawl.com/dtds/suppressions_1_1.dtd) result 404).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://12factor.net/ ([https](https://12factor.net/) result 200). …
=> URL Cleanup

spring-cloud-context/src/main/java/org/springframework/cloud/logging/LoggingRebinder.java, spring-cloud-context/src/test/java/org/springframework/cloud/logging/LoggingRebinderTests.java
=> Apply Spring Boot's solution of coercing `false` LogLevel to `OFF`.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientAutoConfiguration.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/DiscoveryClientAutoConfigurationDefaultTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/ReactiveSimpleDiscoveryPropertiesAutoConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/ServletSimpleDiscoveryPropertiesAutoConfigurationTests.java
=> Use WebServerInitializedEvent to get port for SimpleDiscoveryProperties

spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesBeans.java
This PR migrates away from some Spring Boot classes and methods that were deprecated in https://github.com/spring-projects/spring-boot/issues/16903
=> Migrate from deprecate methods

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceSupplier.java
=> Support reactive discovery client for load balancing

spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/reactive/ReactiveCompositeDiscoveryClient.java, spring-cloud-commons/src/main/java/reactor/core/publisher/CloudFlux.java, spring-cloud-commons/src/main/java/reactor/core/publisher/FluxFirstNonEmptyEmitting.java, spring-cloud-commons/src/test/java/reactor/core/publisher/FluxFirstNonEmptyEmittingTests.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/CachingServiceInstanceListSupplier.java
=> Take first non-empty flux into consideration for composite reactive service discovery

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/pom.xml, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/CaffeineBasedLoadBalancerCacheManager.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/LoadBalancerCacheManager.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/LoadBalancerCacheProperties.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfigurationTests.java
=> caffeine cache for loadbalancer Fix gh 638 

docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc
I edited the Load Balancer and Circuit Breaker sections to make them be consistent with the rest of the document. I tinkered with some other things while I was at it.
=> Making the Load Balancer and Circuit Breaker sections consistent

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/BootstrapOrderingCustomOverrideSystemPropertiesIntegrationTests.java, spring-cloud-context/src/test/resources/ordering.properties
This fixes as revered property source bug.
fixes gh-668
=> Adjusts ordering when override system properties is false.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/DefaultRequest.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/DefaultRequestContext.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/Request.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ReactorLoadBalancer.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LoadBalancerTests.java
=> Add hints to API via the Request interface. Fixes gh-647.

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java, spring-cloud-context/src/test/resources/bootstrap.properties, spring-cloud-context/src/test/resources/external-properties/bootstrap.properties
=> Introduce property spring.cloud.bootstrap.additional-location according to spring.config.additional-location (#466)

spring-cloud-context/src/main/java/org/springframework/cloud/context/scope/GenericScope.java
double checked locking with volatile
=> fix double checked locking with volatile

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/BootstrapPropertySource.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
Move BootstrapPropertySource to its own class and expose delegate PropertySource via getter
=> Refactor BootstrapPropertySource

spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
try to fix https://github.com/spring-cloud/spring-cloud-commons/issues/716  
cc @spencergibb
=> try to fix flaky test

docs/pom.xml, pom.xml, spring-cloud-commons-dependencies/pom.xml, spring-cloud-commons/pom.xml, spring-cloud-context-integration-tests/pom.xml, spring-cloud-context-webflux-integration-tests/pom.xml, spring-cloud-context/pom.xml, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/BootstrapOrderingCustomOverrideSystemPropertiesIntegrationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherOrderingIntegrationTests.java, spring-cloud-context/src/test/resources/ordering.properties, spring-cloud-loadbalancer/pom.xml, spring-cloud-starter/pom.xml, spring-cloud-test-support/pom.xml
=> Port ordering fixes greenwich

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
=> Add predefined ServiceInstanceListSupplier configurations. 

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/SimpleBootstrapPropertySource.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/CachingServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DelegatingServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/CachingServiceInstanceListSupplierTests.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceListSupplierTests.java, src/checkstyle/checkstyle-suppressions.xml
=> Gh 760 health check with cache new

docs/src/main/asciidoc/_configprops.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerProperties.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/SimpleBootstrapPropertySource.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/LoadBalancerCacheProperties.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/DiscoveryClientServiceInstanceListSupplierTests.java
=> Gh 760 fix after review

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RequestData.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ResponseData.java
Also add HttpServerResponse-based constructor to ResponseData.
=> Add HttpServerRequest-based constructor to RequestData.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/SpringCloudApplication.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/EnableCircuitBreaker.java
=> Deprecating @SpringCloudApplication and @EnableCircuitBreaker

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/cache/DefaultLoadBalancerCacheManager.java
=> Use daemon threads with DefaultLoadBalancerCacheManager.

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfigurationTests.java
=> Add CaffeineCacheManager class conditions to LoadBalancerCacheAutoConfiguration

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
=> Instantiate one LoadBalancedRetryFactory bean.

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerServiceInstanceCookieTransformer.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerServiceInstanceCookieTransformerTests.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
=> Add service instance cookie mechanism for blocking load-balanced requests

docs/src/main/asciidoc/_configprops.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerProperties.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RequestBasedStickySessionServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HintBasedServiceInstanceListSupplierTests.java
=> Add hint-based instance filtering

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ExchangeFilterFunctionUtils.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerClientRequestTransformer.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerClientAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunction.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerClientRequestTransformerTest.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionIntegrationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionTests.java
New PR of gh-874 to `2.2.x`
original issue: gh-873
=> Add LoadBalancerClientRequestTransformer to 2.2.x

docs/src/main/asciidoc/_configprops.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerAutoConfiguration.java, spring-cloud-loadbalancer/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Useful for spring-cloud-square tests.
=> Allow disabling load-balancing with property.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/CircuitBreakerFactory.java
Related to [Spring Cloud OpenFeign Issue 514](https://github.com/spring-cloud/spring-cloud-openfeign/issues/514)
=> 2.2.x. Introduce new method in circuit breaker factory 

spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/TaskSchedulerWrapper.java
See https://github.com/spring-cloud/spring-cloud-kubernetes/pull/817#pullrequestreview-686941108 or need for this class
=> Add a TaskSchedulerWrapper for downstream projects to use

spring-cloud-context-integration-tests/pom.xml, spring-cloud-context-integration-tests/src/test/java/org/springframework/cloud/context/integration/JdbcConfigurationTests.java, spring-cloud-context-integration-tests/src/test/java/org/springframework/cloud/context/integration/RefreshScopeIntegrationTests.java
Module spring-cloud-context-integration-tests
=> Upgrade JUnit version (#973)

spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunctionTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshEndpointIntegrationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeConfigurationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeWebIntegrationTests.java
Co-authored-by: Moderne <team@moderne.io>
Using the more specific HTTP verbs where possible.
=> Polish `@RequestMapping` annotations

spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/ReactiveCircuitBreakerFactory.java
=> Fixes gh-994

spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/ReactiveCircuitBreakerFactory.java, spring-cloud-commons/src/main/java/org/springframework/cloud/commons/ConfigDataMissingEnvironmentPostProcessor.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/ConfigDataMissingEnvironmentPostProcessorTests.java
=> Take into account spring.config.imports in referenced imports

spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
to fix: https://github.com/spring-cloud/spring-cloud-sleuth/pull/2024
=> add getter for parent in NamedContextFactory

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerProperties.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
=> Support setting custom port for LB health-checks.

spring-cloud-commons-dependencies/pom.xml
=> Add spring-cloud-test-support.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java
fixed https://github.com/spring-cloud/spring-cloud-commons/issues/1051#issue-1075710606
=> actuate endpoint "actuator/serviceregistry" return object type error

spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ResponseData.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/LoadBalancerTags.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycleTests.java
=> Use raw status codes in ResponseData.

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancerTest.java
=> Enforces the order of RoundRobinLoadBalancer when positive overflow

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancerTest.java
The sign bit is ignored, this allows pos to loop sequentially from 0 to Integer.MAX_VALUE.
So there is no need to check whether positive or negative.
=> Remove unnecessary sign check, whether positive or negative

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ClientHttpResponseStatusCodeException.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/InterceptorRetryPolicy.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRetryPolicy.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerProperties.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerRetryPolicy.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableExchangeFilterFunctionLoadBalancerRetryPolicy.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableStatusCodeException.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/InterceptorRetryPolicyTest.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionIntegrationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionTests.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/retry/BlockingLoadBalancedRetryPolicy.java
=> Custom retry exceptions

docs/src/main/asciidoc/_configprops.adoc, docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerProperties.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ResponseData.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunction.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java
=> Backport support for custom HTTP status in a backwards compatible way.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/RegistrationLifecycle.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/RegistrationManagementLifecycle.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistrationRegistrationLifecycleTests.java
This PR is used to solve this issue[#999](https://github.com/spring-cloud/spring-cloud-commons/issues/999)
=> Adds: RegistrationLifecycle

docs/pom.xml, docs/src/main/asciidoc/_observability.adoc, docs/src/main/asciidoc/appendix.adoc, spring-cloud-commons/pom.xml, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/CircuitBreakerDocumentedObservation.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/CircuitBreakerObservationContext.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/CircuitBreakerObservationConvention.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/DefaultCircuitBreakerObservationConvention.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedCircuitBreaker.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedFunction.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedSupplier.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/circuitbreaker/observation/ObservedCircuitBreakerTests.java
with this change we're introducing Micrometer Observations for CircuitBreakers
=> Support for Micrometer Observations

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/aot/LoadBalancerChildContextInitializer.java
See https://github.com/spring-projects/spring-framework/issues/29005
=> Adapt to API change in Spring Framework

spring-cloud-context/src/main/java/org/springframework/cloud/context/config/annotation/RefreshScope.java
Closes https://github.com/spring-cloud/spring-cloud-commons/issues/1148
=> Add @AliasFor declaration for @RefreshScope

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightFunction.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplier.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilderTests.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplierTest.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplierTests.java
Fixes [gh-1063](https://github.com/spring-cloud/spring-cloud-commons/issues/1063).
=> feat: expand the list by weights to implement weighted load balancing

spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/IdUtils.java, spring-cloud-commons/src/test/java/org/springframework/cloud/commons/util/IdUtilsTests.java
=> Switch default in id from 0 to 8080 if server.port is not set

spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderIntegrationTests.java
=> Destroy and initialize beans within the correct context

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
Enable configuring `WeightedServiceInstanceListSupplier` via `spring.cloud.loadbalancer.configurations`
=> feat: support autoconfigure WeightedServiceInstanceListSupplier

docs/src/main/asciidoc/spring-cloud-commons.adoc
=> Add note about removing configuration values and performing refreshes

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapConfigFileApplicationListener.java
=> Use spring.config.activate.on-profile instead of spring.profiles

docs/src/main/asciidoc/spring-cloud-commons.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfiguration.java, spring-cloud-loadbalancer/src/main/resources/META-INF/spring/aot.factories, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/LoadBalancerCacheAutoConfigurationTests.java
=> Add native hints for Caffeine cache.

docs/src/main/asciidoc/_configprops.adoc, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java, spring-cloud-loadbalancer/src/main/resources/META-INF/additional-spring-configuration-metadata.json
=> Recheck for null service instance to avoid micrometer NPE.

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
=> Add caching to all user-enabled configs other than healthcheck lb.

docs/src/main/asciidoc/spring-cloud-commons.adoc
=> Polish spring-cloud-commons.adoc.

docs/src/main/asciidoc/spring-cloud-commons.adoc
=> note section added for security implications of exposed actuator env.

spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClient.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/composite/CompositeDiscoveryClientUnitTests.java
Fixes https://github.com/spring-cloud/spring-cloud-commons/issues/1209
=> Fixes gh-1209

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java
As you can see, this is the re-submitted pull request.
=> Fix Add a specific description of ServiceInstance is empty

spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DiscoveredResource.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DynamicServiceInstanceProvider.java
The name of the variable is o_O does not conform to Java's naming rules. 
"..." uses the wrong punctuation
=> replace poor punctuation and naming

docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc, docs/modules/ROOT/pages/spring-cloud-commons/loadbalancer.adoc, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/BlockingRestClassesPresentCondition.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalanced.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestTransformer.java, spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRestClientBuilderBeanPostProcessor.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AbstractLoadBalancerAutoConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfigurationTests.java, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerAutoConfigurationTests.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfigurationTests.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSuppliersTestUtils.java
=> @LoadBalanced RestClient

docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
=> Fix typos introduced in RestClient docs

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/TextEncryptorUtils.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionIntegrationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLocationResolver.java, spring-cloud-context/src/test/resources/application-failsafe.properties
Related to https://github.com/spring-cloud/spring-cloud-config/issues/2330
=> Add the ability for FailsafeTextEncryptor to have a delegate.

spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
Modify some methods that do not use constants
=> Using defined constants

spring-cloud-test-support/src/main/java/org/springframework/cloud/test/ModifiedClassPathExtension.java
Higher visibility is needed for: https://github.com/spring-cloud/spring-cloud-netflix/issues/4011.
=> Increase visibility of ModifiedClassPathExtension.

pom.xml, spring-cloud-commons-dependencies/pom.xml, spring-cloud-commons/pom.xml, spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionIntegrationTests.java, spring-cloud-context/pom.xml, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/TextEncryptorConfigBootstrapper.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfiguration.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EncryptionRuntimeHints.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/RsaProperties.java, spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/TextEncryptorUtils.java, spring-cloud-context/src/main/java/org/springframework/cloud/context/encrypt/EncryptorFactory.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfigurationTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionRuntimeHintsTests.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/RsaDisabledTests.java, spring-cloud-starter/pom.xml
In favor of merging into spring-security-crypto
Fixes gh-1398
=> Removes spring-security-rsa

spring-cloud-test-support/pom.xml
`jakarta.validation-api` is transmitted by `hibernate-validator`.
=> Revise dependencies

spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/LoadBalancerTags.java, spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycle.java, spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycleTests.java
=> Handle null in LoadBalancer Request and Response

spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java, spring-cloud-context/src/test/resources/external-properties/bootstrap.yaml
=> Add unit test to verify `spring.config.activate.on-profile` is supported in bootstrap.yaml

spring-cloud-commons-dependencies/pom.xml
=> Use okhttp bom to manage all okhttp dependencies

spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java, spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
Fix fur Issue 1580: https://github.com/spring-cloud/spring-cloud-commons/issues/1580
=> 1580: Fixes property substitution problem for active profiles
