spring-cloud/spring-cloud-commons

- spring-cloud-commons/pom.xml
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/CloudHypermediaAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DiscoveredResource.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/DynamicServiceInstanceProvider.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/RemoteResource.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/RemoteResourceRefresher.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/ServiceInstanceProvider.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/StaticServiceInstanceProvider.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/hypermedia/TraversalDefinition.java
- spring-cloud-commons/src/main/resources/META-INF/spring.factories
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/hypermedia/CloudHypermediaAutoConfigurationIntegrationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/hypermedia/DiscoveredResourceUnitTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/hypermedia/DynamicServiceInstanceProviderUnitTests.java
- spring-cloud-commons/src/test/resources/application.properties
This commit introduces support to easily discover resources in remote service APIs and periodically validating they're still available.
The core concept is a `DiscoveredResource` and its primary implementation `TraversingDiscoveredResource` which consists of a `ServiceInstanceProvider` and a `TraversalDescription`. The service instance provider abstracts the location of the service the `DiscoveredResource` is hosted at. Currently there are two implementations available: a `StaticServiceInstanceProvider` that — as the name suggests — returns a statically configured instance, as well as the `DynamicServiceInstanceProvider` which takes a `DiscoveryClient` and service name as input to dynamically discover the `ServiceInstance` on request.
The `TraversalDefinition` is a SAM type that allows to …
> Added hypermedia support in the form of a DiscoveredResource abstraction

- spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java
As `executorService` could be shut down from another thread, it is not suficient to synchronize its lazy initialization, but it is also required to synchronized its usage in order to prevent another thread from shutting down the `executorService` right before its usage.
As fix is thread-safety oriented, there is not tests intoduced to cover the case.
fixes #132
> Fix #132: Implemented proper synchronization of executorService in InetUtils

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestFactory.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestTransformer.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestFactoryConfigurationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestFactoryTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
Applications can define their own LoadBalancerRequestTransformer beans
which can modify the HttpRequest to be executed. These beans can be
@Ordered in case of multiple transformers.
Fixes #162
> Customize load balanced requests according to the chosen ServiceInstance

- docs/src/main/asciidoc/spring-cloud-commons.adoc
When I set `spring.cloud.loadbalancer.retry=true`,  it is not working. 
According to the source,  `spring.cloud.loadbalancer.retry.enabled=true` is right.
```java
@ConfigurationProperties("spring.cloud.loadbalancer.retry")
public class LoadBalancerRetryProperties {
private boolean enabled = false;
....
}
```
> fixed : Retrying Failed Requests' property is wrong

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
> Provide better error handling for invalid hostnames

- spring-cloud-context/src/main/java/org/springframework/cloud/context/restart/RestartEndpoint.java
- spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/LifecycleMvcAutoConfigurationTests.java
Currently, turning off lifecycle endpoints does not work with the `endpoints.enabled` property. This means the lifecycle endpoints have to be individually disabled 
```
endpoints:
enabled: false
pause:
enabled: false
restart:
enabled: false
resume:
enabled: false
```
This change allows the lifecycle endpoints observe the `endpoints.enabled` property
> Allow lifecycle endpoints to be globally disabled

- docs/src/main/asciidoc/spring-cloud-commons.adoc
Add missing backtick after RestTemplate in order to not have this block huger as intended.
> Close verbatim block properly

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncRestTemplateCustomizer.java
- spring-cloud-commons/src/main/resources/META-INF/spring.factories
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerAutoConfigurationTests.java
> Added classes for async load balancer interceptor

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
Discussed on gitter; if remote `PropertySourceLocator`s such as `ConfigServicePropertySourceLocator` can recursively pull in resources based on the content of their locally defined `spring.profiles.include` property values (this is actually done by the config server itself, but it _is_ done), it follows that those same values should be considered for addition to the `Environment`'s active profiles.
> consider spring.profiles.include values from bootstrap PropertySources

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Fixes #178 : Edge case where if there is a parent context which returns an environment that is not a `ConfigurableEnvironment`, can lead to an infinite loop.
> GH-178: Fixes edge case of a infinite loop in decrypting properties

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AutoServiceRegistrationProperties.java
In continuation of [this PR to spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul/pull/323), I've added option to control management registration to spring-cloud-commons.
> Add option to control management registration

- spring-cloud-context/src/main/java/org/springframework/cloud/context/environment/EnvironmentManager.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/environment/EnvironmentManagerTest.java
When the Environment is resetted the EnvironmentChangedEvent always
contains an empty keySet, since the live view of the cleared map was
used. This commit fixes this.
> Fix empty keys in EnvironmentChangedEvent on resetting the Environment

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfiguration.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionBootstrapConfigurationTests.java
Fixes #230  - Throws an `IllegalStateException` if the keystore location is present but wrong. The second requested issue of handling a case where key is null does not happen as `KeyCondition` would fail.
> Show better message for missing config keystore props

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistration.java
In AbstractAutoServiceRegistration, I suggest to set the property serviceRegistry as final to make code more clear.
> serviceRegistry should set to final to make code more clear

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/AutoServiceRegistrationProperties.java
In class AutoServiceRegistrationProperties, the property failFast is defined after some methodes. 
This is not a good code style and I suggest to move it to the begin of the class and before all the methods.
> move property definition to begin of class to improve code style

- spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
- spring-cloud-context/src/main/resources/META-INF/spring.factories
- spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderListIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderProxyIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinderRefreshScopeIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/MoreRefreshScopeIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeConcurrencyTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeConfigurationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeLazyIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeListBindingIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/scope/refresh/RefreshScopeScaleTests.java
Minor: Replaces all references to deprecated `org.springframework.boot.autoconfigure.PropertyPlaceholderAutoConfiguration` with `org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration`
> Replaces deprecated o.s.b.a.PropertyPlaceholderAutoConfiguration

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ClientHttpResponseStatusCodeException.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryableStatusCodeException.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RibbonRecoveryCallback.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/ClientHttpResponseStatusCodeExceptionTest.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTest.java
These changes are mostly cosmetic in nature and simplifies the recovery callback implementation when retrying requests.  It helps with readability, but also allows for cleaner implementations in downstream projects.
> Refactoring recovery callback implementation

- spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
If `this.refreshables` and `refreshables` are the same instance, invoking `addAll()` isn't necessary.
> Polish RefreshScopeBeanDefinitionEnhancer.setRefreshable()

- spring-cloud-context/src/main/java/org/springframework/cloud/context/encrypt/EncryptorFactory.java
If we repeatedly call String#replaceAll, we internally repeatedly call the regular expression pattern compilation every time as following:
```java
public String replaceAll(String regex, String replacement) {
return Pattern.compile(regex).matcher(this).replaceAll(replacement);
}
```
The modifications are to keep the compiled pattern.
Therefore, compiling a relatively expensive regular expression pattern does not have to be done every time.
> Refactor String#replaceAll

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
MainApplicationClass will be null, if it is booted from SpringBootServletInitializer. So we need to set it properly.
Fixes gh-425
> Set MainApplicationClass if it is null

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapImportSelector.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapImportSelectorConfiguration.java
This change moves a dynamic list of classes passed to
`SpringApplicationBuilder.sources` to a `DeferredImportSelector` loaded
by a simple `@Configuration` class. `BootstrapImportSelector` now loads
the classes and orders them and returns the class names so that
`@Conditional` annotations (such as `@ConditionalOnClass`) function
properly.
This was exposed while using java 11.
fixes gh-438
Still needs a test, but the code @mp911de posted here https://github.com/spring-projects/spring-boot/issues/14873#issuecomment-434051815 works properly.
/cc @wilkinsona
> Moves BootstrapConfiguration classes to ImportSelector.

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Since the decrypted property source is taking precedence over all other property sources, it would not allow encrypted properties to be overridden by unencrypted properties. This commit removes the decrypted property from the overrides if it gets overridden by an unencrypted property.
Replaces #457
> Allow overriding encrypted properties with unencrypted properties

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Since decryption can be expensive (e.g. an http request needs to be made) or just not possible (in tests), it can be beneficial to not attempt to decrypt properties that get overridden anyway.
In this PR the decryption is postponed until after all the overrides are gathered.
Side effect is that `failOnError` will only fail if the property does not get overridden.
> Only attempt to decrypt properties that are not overridden

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
The issue #471 is actually related to https://github.com/spring-cloud/spring-cloud-commons/pull/358 (which just activated an hidden issue). The propertySources from CompositePropertySource should be walked in reversed order for the overrides to behave properly. 
Fixes gh-471
> Fix override behaviour when using CompositePropertySource.

- 1.0.x/ghpages.sh
- 1.2.x/ghpages.sh
- 1.3.x/ghpages.sh
- 2.0.x/ghpages.sh
- 2.1.x/ghpages.sh
- ghpages.sh
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch with 6 occurrences migrated to:  
https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch ([https](https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch) result 200).
* http://stackoverflow.com/questions/29300806/a-bash-script-to-check-if-a-string-is-present-in-a-com …
> URL Cleanup

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializerTests.java
Reversed order of sources in `CompositePropertySource` to adhere to the order of sources returned by the Spring Cloud Config server.
Fixes #574
> Changed order of decrypting values.

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/support/OriginTrackedCompositePropertySource.java
This allows the boot origin tracking mechanism to work if bootstrap loaded propertysources themselves are also origin tracked.
See https://github.com/spring-cloud/spring-cloud-config/issues/866
> Adds OriginTrackedCompositePropertySource for bootstrap

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceLocator.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherTests.java
- spring-cloud-context/src/test/resources/bootstrap.properties
> Add each PropertySource from PropertySourceLocators individually

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/ServiceInstance.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplierTests.java
> Zoned ServiceInstanceListSupplier

- docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/circuitbreaker/Customizer.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/circuitbreaker/CustomizerTests.java
This PR adds `once` method to `org.springframework.cloud.client.circuitbreaker.Customizer` that guarantees `customize` method is called at most once per target.
Some `CircuitBreaker` implementations such as `Resilience4JCircuitBreaker` calls `customize` method every time `CircuitBreaker#run` is called.  It is sometimes inefficient and troublesome.
Using `once` method is useful where calling `customize` many times doesn't make sense,
for example, in case of [consuming Resilience4j's  events](https://resilience4j.readme.io/docs/circuitbreaker#section-consume-emitted-circuitbreakerevents).
Here is an example for each `io.github.resilience4j.circuitbreaker.CircuitBreaker` to consume events. 
```java
Customizer.once(circuitBreaker -> {
circuitBreaker.getEventPublisher() …
```
> Add once method for Customizer of circuit breaker

- spring-cloud-loadbalancer/pom.xml
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
- WebClient response leaks
- potential Scheduled task leak
- rework polling to plain reactor operators
- remove non atomic operations on ServiceInstance lists
original issue gh-683
related to gh-629
> Fixes issues in HealthCheckServiceInstanceListSupplier

- spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
- spring-cloud-context/src/test/java/org/springframework/cloud/AdhocTestSuite.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherOrderingIntegrationTests.java
Updates the targetName so that property sources maintain ordering from the bootstrap environment where they were refreshed.
Fixes gh-704
> Updates ContextRefresher to maintain property source ordering.

- docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
Typo correction in document
netfix -> netflix
> Typo correction in document

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpoint.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpointTests.java
fix https://github.com/spring-cloud/spring-cloud-commons/issues/458
> fix Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-context/src/main/java/org/springframework/cloud/util/random/CachedRandomPropertySource.java
- spring-cloud-context/src/main/java/org/springframework/cloud/util/random/CachedRandomPropertySourceAutoConfiguration.java
- spring-cloud-context/src/main/resources/META-INF/spring.factories
- spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ContextRefresherIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/util/random/CachedRandomPropertySourceTests.java
- spring-cloud-context/src/test/resources/META-INF/spring.factories
- spring-cloud-context/src/test/resources/application.properties
This would allow the application to be refreshed and still get the same random value the next time the application needs one.
> Add a property source that produces a random value that is cached

- spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/IdUtils.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/commons/util/IdUtilsTests.java
This is moving a utility method from Spring Cloud Bus to commons for more reuse.
I decided against replacing `getDefaultInstanceId` with this new method as I think conceptually a instance id is different than a service id.
> Add a utility method to provide a default service id

- spring-cloud-commons/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-context/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> The default value for management.endpoint.env.post.enabled configuration metadata should be false instead of true.

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientAutoConfiguration.java
This PR fixes GraalVM native compatibility since for some reasons field autowiring in configuration is not working. Regardless on that issue, I think Spring Boot autoconfiguration has removed such usage and it would be nice for Spring Cloud to do the same (there are probably other similar usages).
> Avoid field autowiring in SimpleDiscoveryClientAutoConfiguration

- spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/named/NamedContextFactoryTests.java
> Performance improvements to NamedContextFactory.

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/InterceptorRetryPolicy.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRetryProperties.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerProperties.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/AbstractLoadBalancerAutoConfigurationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/InterceptorRetryPolicyTest.java
- spring-cloud-loadbalancer/pom.xml
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/retry/BlockingLoadBalancedRetryFactory.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/retry/BlockingLoadBalancedRetryPolicy.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/blocking/retry/BlockingLoadBalancedRetryPolicyTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfigurationTests.java
> Add retry support for blocking LoadBalancer

- docs/src/main/asciidoc/ghpages.sh
- docs/src/main/asciidoc/spring-cloud-circuitbreaker.adoc
> Wording changes

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClient.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryProperties.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/reactive/SimpleReactiveDiscoveryClientAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/reactive/SimpleReactiveDiscoveryProperties.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/reactive/SimpleReactiveDiscoveryClientTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerExchangeFilterFunctionTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunctionTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClientTests.java
Please review the code changes for the Issue 824 (https://github.com/spring-cloud/spring-cloud-commons/issues/824)
Unit Tests passed locally via mvn install -P spring
> Deprecates SimpleServiceInstance in favor of DefaultServiceInstance

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerProperties.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
> Allow refetching instances for healthcheck

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/SameInstancePreferenceServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/SelectedInstanceCallback.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LoadBalancerTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/SameInstancePreferenceServiceInstanceListSupplierTests.java
> Support same service instance preference

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ExchangeFilterFunctionUtils.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerProperties.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunction.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RequestBasedStickySessionServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RequestBasedStickySessionServiceInstanceListSupplierTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ZonePreferenceServiceInstanceListSupplierTests.java
> Request based sticky session

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfigurationTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/CachingServiceInstanceListSupplierTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSuppliersTestUtils.java
> Add function-based health check. Add restTemplate-based health-check beans to default config

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AsyncLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/CompletionContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/HintRequestContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerLifecycle.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRequestAdapter.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RequestDataContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/ResponseData.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryableRequestContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/TimedRequestContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunction.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptorTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunctionTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionIntegrationTests.java
- spring-cloud-loadbalancer/pom.xml
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClient.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/LoadBalancerStatsAutoConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/LoadBalancerTags.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLifecycle.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycle.java
- spring-cloud-loadbalancer/src/main/resources/META-INF/spring.factories
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/blocking/client/BlockingLoadBalancerClientTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/stats/MicrometerStatsLoadBalancerLifecycleTests.java
> Lb micrometer stats

- README.adoc
- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRetryProperties.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryableRequestContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ExchangeFilterFunctionUtils.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerRetryContext.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerRetryPolicy.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactorLoadBalancerExchangeFilterFunction.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableExchangeFilterFunctionLoadBalancerRetryPolicy.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunction.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableStatusCodeException.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionIntegrationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/reactive/RetryableLoadBalancerExchangeFilterFunctionTests.java
> Backport retryable lb exchange filter function

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
Fixes gh-899
(cherry picked from commit 3d257b43003a02b64c4f7fd97680e7981d0b52f4)
> Fix bug of service instance refetching when repeating health check is activated

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LoadBalancerServiceInstanceCookieTransformer.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LoadBalancerServiceInstanceCookieTransformerTests.java
Keep the class with the autoconfiguration that uses it.
> Move LoadBalancerServiceInstanceCookieTransformer to loadbalancer module

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/DiscoveryClient.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/ReactiveDiscoveryClient.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/health/DiscoveryClientHealthIndicator.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/health/DiscoveryClientHealthIndicatorProperties.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/health/reactive/ReactiveDiscoveryClientHealthIndicator.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/health/DiscoveryClientHealthIndicatorUnitTests.java
Adds a probe method to Reactive/DiscoveryClient and optionally use in Reactive/DiscoveryClientHealthIndicator.
Fixes gh-785.
@ryanjbaxter - here is the 2.2.x version.
> Add probe method to DiscoveryClient 

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
Should use ConditionalOnReactiveDiscoveryEnabled on ReactiveRetryConfiguration, not ConditionalOnBlockingDiscoveryEnabled
> rewrite annotation on ReactiveRetryConfiguration

- spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresher.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/encrypt/EncryptionIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresherIntegrationTests.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLoader.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataLocationResolver.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestConfigDataResource.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/test/TestEnvPostProcessor.java
- spring-cloud-context/src/test/resources/META-INF/spring.factories
- spring-cloud-context/src/test/resources/application.properties
This includes ConfigDataEnvironmentPostProcessors which replaces the static call.
Issue #968 was specifically about the cloud foundry vcap post processor. Previously the DecryptEnvironmentPostProcessor was hard coded in ConfigDataContextRefresher
Fixes gh-968
> Run all EnvironmentPostProcessors on refresh.

- docs/src/main/asciidoc/spring-cloud-commons.adoc
It was 
> Although the basic, non-cached, implementation is useful for prototyping and testing, it’s much less efficient than the cached versions, so we recommend always using the cached version in production.
Added load-balancer cashe configuration warnings about double caching and changed to:
> Although the basic, non-cached, implementation is useful for prototyping and testing, it’s much less efficient than the cached versions, so we recommend always using the cached version in production. If the caching is already done by the `DiscoveryClient ` implementation, for example `EurekaDiscoveryClient`, the load-balancer caching should be disabled to prevent double caching.
> Added load-balancer cashe configuration warnings #775

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
Add `with()` method to support external `ServiceInstanceListSupplier` extension(#988)
> Add `with()` method to support external ServiceInstanceListSupplier(#988)

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
new StandardEnvironment will add systemProperties/systemEnvironment PropertySource within its constructor which we do not need.
**we should not create object which do something we do not want, then undo it**
> fix: remove unnecessary code

- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/config/XForwardedConfigurationCondition.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/support/LoadBalancerClientFactory.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/support/LoadBalancerEnvironmentPropertyUtils.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LoadBalancerTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/support/LoadBalancerEnvironmentPropertyUtilsTests.java
Make properties other than within `@ConfigurationProperties` work per-client, with the following global properties exclusions:
- `spring.cloud.loadbalancer.enabled`
- `spring.cloud.loadbalancer.retry.enabled` - if enabled, still possible to disable per-client only with properties
- `spring.cloud.loadbalancer.cache.enabled` - if enabled, still possible to disable per-client with custom configuration
- `spring.cloud.loadbalancer.stats.micrometer.enabled`
Fixes gh-1031.
> Handle conditionals for client properties

- spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java
Only for 3.0.x branch, since 3.1.x targets Spring Boot 2.6+.
```java
/**
* Restrictions that can be applied when binding values.
*
* @since 2.5.0
*/
public enum BindRestriction {
```
> Fix is2_5 comment

- spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/IdUtils.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/commons/util/IdUtilsTests.java
New constant IdUtils.DEFAULT_SERVICE_ID_WITH_ACTIVE_PROFILES_STRING refers to profiles in second position.
IdUtils.getResolvedServiceId chooses new constant as template only if profiles are active, and thus remains backwards-compatible.
Add unit tests for new behaviour.
Fixes gh-930.
> Consider spring.profiles.active when resolving service ID.

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientTests.java
The current DefaultServiceInstance getUri() method does not support URIs without a port. This is problematic when using the Spring Cloud Loadbalancer for DNS subdomain-based targets. For example service instances in different K8 clusters/CF foundations. This pull request adds a simple condition for constructing the uri string based on the port being > 0.
> Support uri without port for default service instance

- docs/src/main/asciidoc/spring-cloud-commons.adoc
I've read docs (https://docs.spring.io/spring-cloud-commons/docs/3.1.1/reference/html/#retrying-failed-requests) and found a missing character `.
> Fix typo in spring-cloud-commons.adoc

- spring-cloud-context/src/main/java/org/springframework/cloud/context/named/NamedContextFactory.java
- spring-cloud-context/src/test/java/org/springframework/cloud/context/named/NamedContextFactoryTests.java
`ConditionEvaluator` extracts the class loader from the bean factory at instantiation, and then uses said classloader to load classes when evaluating conditionals. Hence, we need to inject the parent class loader into a bean factory that we inject into the child context. This fix is an extension of the fix made in spring-cloud/spring-cloud-netflix#3101.
Fixes spring-cloud/spring-cloud-openfeign#475
> Inject the class loader from the parent context into the child context

- spring-cloud-commons-dependencies/pom.xml
Upgrading spring-security-rsa from 1.0.10 to 1.0.11
indirectly upgrades org.bouncycastle:bcprov-jdk15on from 1.68 to 1.69
to fix Cryptographic Issues via weak key-hash message authentication code (HMAC)
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-2841508
@pivotal-cla This is an Obvious Fix
> Bump spring-security-rsa to 1.0.11

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancerTests.java
Fixes [gh-1144](https://github.com/spring-cloud/spring-cloud-commons/issues/1144)
Do not move position when there is only 1 instance, especially some suppliers have already filtered instances.
> Do not move position when there is only 1 instance

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceList.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/WeightedServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceListTest.java
When we have a lot of upstream services, and their total weight is large, then if we expand all instances in one request, our processing time will be very long. To solve this problem, use a lazily computed list to expand all elements to an unexpanded position only when the unexpanded position is visited.
There is an extreme case here. When using `RandomLoadBalancer`, it is possible to select a very late node for the first time, so the delay will still be large. But when we use `RoundRobinLoadBalancer`, we only move the position of one element at a time, so the effect is negligible.
> Lazy fills service instances to reduce max latency

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/DefaultServiceInstance.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryProperties.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientPropertiesMappingTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryClientTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/HealthCheckServiceInstanceListSupplierTests.java
> Allow overriding getScheme on DefaultServiceInstance.

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
Enables to easily create custom load balancer configurations with zone preference, but a different zone then the one defined by spring.cloud.loadbalancer.zone
> Add flexibility to zone preference in load balancing

- spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java
I found to use this class name [ValidationConfigurationCustomizer](https://github.com/spring-projects/spring-boot/blob/ad63cb8e620097e2ad5bccf3af67e76dc87c528f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/logging/ConditionEvaluationReportLoggingListener.java#L50) to verify the compatibility for Spring Boot 3,
https://github.com/spring-cloud/spring-cloud-commons/blob/f26c2b3e933572c659e2925aea815bdf77f3372b/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java#L86, but this class has already existed since Spring Boot 2.
I am going to replace it with a new class [ValidationConfigurationCustomizer ](https://github.com/spring-projects/spring-boot/blob/ed5fe2d26ec4abad88f49005b499602dae4daa …
> Update the compatibility verification class name for Spring Boot 3

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/LazyWeightedServiceInstanceList.java
The implemented logic is the same as #1184, both are O(1) schedulers, but the code implementation is simplified through double queues, and recursive processing that may cause errors is avoided
> Refactor code to simplify calculation logic

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/ReactiveDiscoveryClient.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/health/reactive/ReactiveDiscoveryClientHealthIndicator.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/discovery/health/reactive/ReactiveDiscoveryClientHealthIndicatorTests.java
- src/checkstyle/checkstyle-suppressions.xml
> Add Reactive probe

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java
Fixes #1229 | @ryanjbaxter I have updated it as you suggested.  I also saw that bean was formed successfully with `CommonsClientAutoConfigurationTests` : 
> _org.springframework.beans.factory.support.DefaultListableBeanFactory -- Creating shared instance of singleton bean '**springCloudCommonsFeatures**'_
> commonsFeatures method name updated to springCloudCommonsFeatures. 

- docs/src/main/asciidoc/_configprops.adoc
- docs/src/main/asciidoc/spring-cloud-commons.adoc
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapApplicationListener.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java
- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapProperties.java
- spring-cloud-context/src/test/java/org/springframework/cloud/bootstrap/config/BootstrapConfigurationTests.java
Also adds support for activating profiles using spring.profiles.active from bootstrap property source listeners.
> Add application listener to locate property sources during bootstrap

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/DelegatingServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/SameInstancePreferenceServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RetryAwareServiceInstanceListSupplierTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancerTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/SameInstancePreferenceServiceInstanceListSupplierTests.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/TestSelectedServiceInstanceSupplier.java
respect `SelectedInstanceCallback` on its delegate. Motivation behind is that some load balancer implementations like the `RoundRobinLoadBalancer` to call `selectedServiceInstance` on the `ServiceInstanceListSupplier` after choosing the next instance. However, when a `ServiceInstanceListSupplier` in wrapped by the `DelegatingServiceInstanceListSupplier` this functionality breaks, as `DelegatingServiceInstanceListSupplier` is not implementing `SelectedInstanceCallback` and therefore does ignoring that its delegate might also do. This might break the functionality of the delegate. Fixes gh-1221.
> Fix DelegatingServiceInstanceListSupplier must

- docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/endpoint/ServiceRegistryEndpointNoRegistrationTests.java
> Fix "Service Registry Actuator Endpoint URL" in doc is wrong(#1240)

- spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/BootstrapConfigFileApplicationListener.java
This PR changes the order of the `BootstrapConfigFileApplicationListener` to  make sure that the `BootstrapConfigFileApplicationListener` always is executed after the `ConfigDataEnvironmentPostProcessor`.
**The reason**
The `BootstrapConfigFileApplicationListener`  relies on the `Environment.activeProfiles` to have been set correctly, like for instance with the `SpringApplication.additionalProfiles`. The environment post processor responsible for setting the `Environment.activeProfiles` correctly (e.g. by adding the `SpringApplication.additionalProfiles`) is the `org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor`. If it runs before the `BootstrapConfigFileApplicationListener` then everything works correctly. However both the …
> Fixed order of the `BootstrapConfigFileApplicationListener` so that it always runs after the `ConfigDataEnvironmentPostProcessor`

- docs/modules/ROOT/pages/spring-cloud-commons/loadbalancer.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerProperties.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/ServiceInstanceListSupplierBuilder.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/SubsetServiceInstanceListSupplier.java
- spring-cloud-loadbalancer/src/test/java/org/springframework/cloud/loadbalancer/core/SubsetServiceInstanceListSupplierTest.java
[gh-1288](https://github.com/spring-cloud/spring-cloud-commons/issues/1288)
> feat(lb): deterministic subsetting algorithm

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/BlockingLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/DeferringLoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRestClientBuilderBeanPostProcessor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerInterceptor.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRestClientIntegrationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfigurationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/RetryLoadBalancerAutoConfigurationTests.java
Load balanced RestClient with deferring postprocessor.
> Allow building @LoadBalanced RestClient in component constructor.

- docs/modules/ROOT/pages/spring-cloud-commons/loadbalancer.adoc
This PR fixes the broken section header in the LoadBalancer Caching documentation:
> Fix Caffeine section header in LoadBalancer caching documentation

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/LoadBalancerBeanPostProcessorAutoConfiguration.java
The PR resolves the remaining warnings about beans not being eligible for getting processed by all `BeanPostProcessor`s. Similar warnings have been reported in #1315 and fixed in #1319.
The warnings do not indicate a severe issue. But they lead to confusion among users and bad getting started experiences. And as the size of the PR shows, the required change is rather small.
The effectiveness of the change can be seen in the following tests:
- `LoadBalancerRequestFactoryConfigurationTests`
- `ReactorLoadBalancerClientAutoConfigurationTests`
Without the change, the test `LoadBalancerRequestFactoryConfigurationTests` logs the following warnings:
```
Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration$DeferringLoadBalancerInterceptorConfig' of type …
```
> Resolve bean post processor warnings

- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RandomLoadBalancer.java
- spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/core/RoundRobinLoadBalancer.java
Each time instance selection is performed during a request, the `ObjectProvider#getIfAvailable` method is called, and its reflection implementation causes some CPU consumption.
> Optimize instance selection performance

- spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SSLContextFactory.java
Addresses this issue https://github.com/spring-cloud/spring-cloud-config/issues/2514
Tests for this can be found in this PR https://github.com/spring-cloud/spring-cloud-config/pull/2543
> Create truststore without keystore

- spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java
See https://github.com/spring-cloud/spring-cloud-commons/issues/1364
> Use newCachedTreadPool() instead of newSingleThreadExecutor() in InetUtils

- docs/modules/ROOT/pages/spring-cloud-commons/common-abstractions.adoc
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/AbstractLoadBalancerBlockingBuilderBeanPostProcessor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRestClientBuilderBeanPostProcessor.java
- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerRestTemplateBuilderBeanPostProcessor.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRestClientIntegrationTests.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/loadbalancer/LoadBalancedRestTemplateBuilderIntegrationTests.java
> Support @LoadBalanced RestTemplateBuilder

- spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
It should be fixed at Spring Boot side, see https://github.com/spring-projects/spring-boot/commit/2f83a6714bf258c3fcc8ca92c89f02cf2043c97a
> Remove workaround for data source cycle

- spring-cloud-context/src/main/java/org/springframework/cloud/env/EnvironmentUtils.java
EnvironmentUtils is not used in all spring-cloud projects, see https://github.com/search?q=org%3Aspring-cloud%20getSubProperties&type=code
> Deprecate unused EnvironmentUtils

- spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ConfigDataContextRefresher.java
- spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
- spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/LegacyContextRefresher.java
It's specific to LegacyContextRefresher.
> Move field ContextRefresher.REFRESH_ARGS_PROPERTY_SOURCE down to LegacyContextRefresher

- docs/modules/ROOT/partials/_configprops.adoc
- spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java
- spring-cloud-context/src/main/java/org/springframework/cloud/context/properties/ConfigurationPropertiesRebinder.java
- spring-cloud-context/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-context/src/test/java/org/springframework/cloud/autoconfigure/RefreshAutoConfigurationTests.java
Thanks to https://github.com/spring-projects/spring-boot/issues/22403, applications could define a bean in addition to an auto-configured bean of the same type, then we should support configuring bean names for fine-grained control.
> Support configuring bean names as well as bean types for extra-refreshable and never-refreshable

- spring-cloud-commons-dependencies/pom.xml
- spring-cloud-commons/pom.xml
[Spring Boot 3.4.0 no longer manages the version of okhttp](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#okhttp-dependency-management-removed).  To maintain backward compatibility we should manage it here in Spring Cloud Commons
> Manage the version of okhttp in commons

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerAutoConfiguration.java
>> Generally, auto-configuration classes are top-level classes
> Fix incorrect usage of `@AutoConfiguration`

- spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/event/InstanceRegisteredEvent.java
- spring-cloud-commons/src/test/java/org/springframework/cloud/client/serviceregistry/AbstractAutoServiceRegistrationTests.java
> Make InstanceRegisteredEvent implements ResolvableTypeProvider
